const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Turret,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Turret.Exps.Range,
		C3.Plugins.System.Exps.rgbex,
		C3.Behaviors.Turret.Acts.SetRange,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Fade.Cnds.OnWaitEnd,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{binansuo: 0},
	{sy: 0},
	{interal: 0},
	{hp: 0},
	{hpmax: 0},
	{Solid: 0},
	{fadianchang: 0},
	{atk: 0},
	{lv: 0},
	{Turret: 0},
	{Tween: 0},
	{paotai: 0},
	{cankao: 0},
	{ui_dianli: 0},
	{Timer: 0},
	{ui_daojishi: 0},
	{ui_boci: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{paodan: 0},
	{getBulilding: 0},
	{base: 0},
	{puid: 0},
	{Pin: 0},
	{role_hp3: 0},
	{role_hp2: 0},
	{role_hp1: 0},
	{hpwidth: 0},
	{boss_hp2: 0},
	{boss_hp1: 0},
	{boss_hp3: 0},
	{skillbg: 0},
	{icon_skill1: 0},
	{icon_skill2: 0},
	{icon_skill3: 0},
	{eny_hp3: 0},
	{eny_hp2: 0},
	{eny_hp1: 0},
	{state: 0},
	{nextState: 0},
	{role_1: 0},
	{Touch: 0},
	{MoveTo: 0},
	{Pathfinding: 0},
	{role_proxy: 0},
	{maxhp: 0},
	{Fade: 0},
	{eny_1: 0},
	{typeid: 0},
	{ui_numberText: 0},
	{paodan_ef: 0},
	{Sine: 0},
	{update: 0},
	{LocalStorage: 0},
	{newbiebg: 0},
	{newbieround: 0},
	{newbiehandbg: 0},
	{newbiehand: 0},
	{talkbg: 0},
	{talkbgText: 0},
	{tips: 0},
	{buildingType: 0},
	{pid: 0},
	{ef_repair: 0},
	{eny_hurttext: 0},
	{icondianli: 0},
	{dianlitext: 0},
	{ef_skill: 0},
	{Bullet2: 0},
	{bomb: 0},
	{bomb_ef: 0},
	{eny_boss: 0},
	{role_3: 0},
	{ui_tips: 0},
	{ui_itembbg: 0},
	{ui_itembg: 0},
	{btnid: 0},
	{ui_itembtn: 0},
	{ui_itemclosebtn: 0},
	{itemID: 0},
	{basePid: 0},
	{itemBtn: 0},
	{Rotate: 0},
	{paotairange: 0},
	{solidwall: 0},
	{ui_jinbi: 0},
	{jinbitext: 0},
	{itemrole: 0},
	{paitaiicon: 0},
	{gold: 0},
	{paotaitext: 0},
	{roleid: 0},
	{roletext: 0},
	{wall: 0},
	{wall_hp4: 0},
	{wall_hp5: 0},
	{wall_hp6: 0},
	{btn_restart: 0},
	{gameText: 0},
	{Flash: 0},
	{bosstext: 0},
	{Keyboard: 0},
	{ui_updatebg: 0},
	{ui_updateicon: 0},
	{ui_updatebtn: 0},
	{updatetext: 0},
	{Anchor: 0},
	{uiicons: 0},
	{objs: 0},
	{hps: 0},
	{uibtns: 0},
	{Timer2: 0},
	{enys: 0},
	{finishnewbie: 0},
	{gamestart: 0},
	{gameturnTimer: 0},
	{turnTimer: 0},
	{bossturn: 0},
	{gameturns: 0},
	{gamesdianli: 0},
	{gamesgold: 0},
	{curpanel: 0},
	{getrole_2: 0},
	{getrole_3: 0},
	{result: 0},
	{talking: 0},
	{enysType: 0},
	{enyPid: 0},
	{hurtValue: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	binansuo: class extends self.ISpriteInstance {},
	fadianchang: class extends self.ISpriteInstance {},
	paotai: class extends self.ISpriteInstance {},
	cankao: class extends self.ISpriteInstance {},
	ui_dianli: class extends self.ISpriteInstance {},
	ui_daojishi: class extends self.ISpriteInstance {},
	ui_boci: class extends self.ISpriteInstance {},
	paodan: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	role_hp3: class extends self.ITiledBackgroundInstance {},
	role_hp2: class extends self.ITiledBackgroundInstance {},
	role_hp1: class extends self.ITiledBackgroundInstance {},
	boss_hp2: class extends self.ITiledBackgroundInstance {},
	boss_hp1: class extends self.ITiledBackgroundInstance {},
	boss_hp3: class extends self.ITiledBackgroundInstance {},
	skillbg: class extends self.ISpriteInstance {},
	icon_skill1: class extends self.ISpriteInstance {},
	icon_skill2: class extends self.ISpriteInstance {},
	icon_skill3: class extends self.ISpriteInstance {},
	eny_hp3: class extends self.ITiledBackgroundInstance {},
	eny_hp2: class extends self.ITiledBackgroundInstance {},
	eny_hp1: class extends self.ITiledBackgroundInstance {},
	role_1: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	role_proxy: class extends self.ISpriteInstance {},
	eny_1: class extends self.ISpriteInstance {},
	ui_numberText: class extends self.ITextInstance {},
	paodan_ef: class extends self.ISpriteInstance {},
	update: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	newbiebg: class extends self.ITiledBackgroundInstance {},
	newbieround: class extends self.ISpriteInstance {},
	newbiehandbg: class extends self.ISpriteInstance {},
	newbiehand: class extends self.ISpriteInstance {},
	talkbg: class extends self.ISpriteInstance {},
	talkbgText: class extends self.ITextInstance {},
	tips: class extends self.ISpriteInstance {},
	ef_repair: class extends self.ISpriteInstance {},
	eny_hurttext: class extends self.ITextInstance {},
	icondianli: class extends self.ISpriteInstance {},
	dianlitext: class extends self.ITextInstance {},
	ef_skill: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	bomb_ef: class extends self.ISpriteInstance {},
	eny_boss: class extends self.ISpriteInstance {},
	role_3: class extends self.ISpriteInstance {},
	ui_tips: class extends self.ITextInstance {},
	ui_itembbg: class extends self.ITiledBackgroundInstance {},
	ui_itembg: class extends self.ISpriteInstance {},
	ui_itembtn: class extends self.ISpriteInstance {},
	ui_itemclosebtn: class extends self.ISpriteInstance {},
	itemBtn: class extends self.ISpriteInstance {},
	paotairange: class extends self.ISpriteInstance {},
	solidwall: class extends self.ITiledBackgroundInstance {},
	ui_jinbi: class extends self.ISpriteInstance {},
	jinbitext: class extends self.ITextInstance {},
	itemrole: class extends self.ISpriteInstance {},
	paitaiicon: class extends self.ISpriteInstance {},
	gold: class extends self.ISpriteInstance {},
	paotaitext: class extends self.ITextInstance {},
	roletext: class extends self.ITextInstance {},
	wall: class extends self.ISpriteInstance {},
	wall_hp4: class extends self.ITiledBackgroundInstance {},
	wall_hp5: class extends self.ITiledBackgroundInstance {},
	wall_hp6: class extends self.ITiledBackgroundInstance {},
	btn_restart: class extends self.ITextInstance {},
	gameText: class extends self.ITextInstance {},
	bosstext: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	ui_updatebg: class extends self.ISpriteInstance {},
	ui_updateicon: class extends self.ISpriteInstance {},
	ui_updatebtn: class extends self.ISpriteInstance {},
	updatetext: class extends self.ITextInstance {},
	uiicons: class extends self.ISpriteInstance {},
	objs: class extends self.ISpriteInstance {},
	hps: class extends self.ITiledBackgroundInstance {},
	uibtns: class extends self.ISpriteInstance {},
	enys: class extends self.ISpriteInstance {}
}